[package]
name = "tipos_rasgos_genericos"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
cairo_execute = "2.11.2+nightly-2025-03-12"

[dev-dependencies]
cairo_test = "2.11.2"

[[target.executable]]
name = "datos_genericos"
source = "src/datos_genericos.cairo"

[[target.executable]]
name = "trait_in_cairo"
source = "src/trait_in_cairo.cairo"

[cairo]
enable-gas = false
