[package]
name = "ownership"
version = "0.1.0"
edition = "2024_07"


[dependencies]
cairo_execute = "2.11.2"

[dev-dependencies]
snforge_std = "0.38.0"
assert_macros = "2.11.2"

[[target.executable]]
main = "src/lib.cairo"
sierra = true
casm = true

[lib]
sierra = true
casm = true

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[cairo]
enable-gas = false
