[package]
name = "referencias_instantaneas"
version = "0.1.0"
edition = "2024_07"

[dependencies]
cairo_execute = "2.10.1"
starknet = "2.10.1"

[lib]
sierra = true
casm = true

[[target.executable]]
name = "run_instantanea"
function = "referencias_instantaneas::instantanea::run_instantanea"
sierra = true
casm = true

[[target.executable]]
name = "run_referencias_mutables"
function = "referencias_instantaneas::referencias_mutables::run_referencias_mutables"
sierra = true
casm = true

[dev-dependencies]
snforge_std = "0.38.0"
assert_macros = "2.10.1"

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[cairo]
enable-gas = false
