[package]
name = "fibonacci"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
cairo_execute = "2.11.4"
starknet = ">=2.3.1"

[dev-dependencies]
cairo_test = "2.11.4"

[cairo]
enable-gas = true

[[target.executable]]
name = "fibonacci"
source = "src/lib.cairo"