[package]
name = "error_handling"
version = "0.1.0"
edition = "2024_07"

[dependencies]
cairo_execute = "2.11.2+nightly-2025-03-12"

[dev-dependencies]
cairo_test = "2.11.2"

[[target.executable]]
name = "irrecuperables"
function = "error_handling::errores_irrecuperables::irrecuperables"

[[target.executable]]
name = "result_examples"
function = "error_handling::recuperables_result::result_examples"

[cairo]
enable-gas = false