[package]
name = "estructuras"
version = "0.1.0"
edition = "2024_07"

[dependencies]
cairo_execute = "2.10.1"
starknet = "2.10.1"

[lib]
sierra = true
casm = true

[[target.executable]]
name = "usuario"
function = "estructuras::struct_practica::usuario"
sierra = true
casm = true

[[target.executable]]
name = "pregunta1"
function = "estructuras::struct_pregunta_1::pregunta1"
sierra = true
casm = true

[[target.executable]]
name = "pregunta2"
function = "estructuras::struct_pregunta_2::pregunta2"
sierra = true
casm = true

[[target.executable]]
name = "geometrico"
function = "estructuras::struct_geometria::geometrico"
sierra = true
casm = true

[dev-dependencies]
snforge_std = "0.38.0"
assert_macros = "2.10.1"

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[cairo]
enable-gas = false