[package]
name = "zkp"
version = "0.1.0"
edition = "2024_07"

[[target.executable]]
name = "n_primo"
function = "zkp::prime_prover::n_primo"
sierra = true
casm = true

[[target.executable]]
name = "numero_par"
function = "zkp::par_prover::numero_par"
sierra = true
casm = true

[cairo]
enable-gas = false

[dependencies]
cairo_execute = "2.10.0"
starknet = "2.10.1"

[dev-dependencies]
snforge_std = "0.38.0"
assert_macros = "2.10.1"

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]
