# Visit https://foundry-rs.github.io/starknet-foundry/appendix/snfoundry-toml.html
# and https://foundry-rs.github.io/starknet-foundry/projects/configuration.html for more information

[sncast.default]
url = "https://free-rpc.nethermind.io/sepolia-juno/v0_7"
accounts-file = "../../.starknet_accounts/starknet_open_zeppelin_accounts.json"
account = "braavos"
block-explorer = "StarkScan"
show-explorer-links = true
