[package]
name = "diccionario"
version = "0.1.0"
edition = "2024_07"

[[target.executable]]
name = "balance_usuarios"
function = "diccionario::dict_ejemplo1::balance_usuarios"
sierra = true
casm = true

[dependencies]
cairo_execute = "2.10.1"
starknet = "2.10.1"

[dev-dependencies]
snforge_std = "0.38.0"
assert_macros = "2.10.1"

[scripts]
test = "snforge test"

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[cairo]
enable-gas = false